### ISSUE TITLE
form definition for html rendering

### ISSUE THREAD

**Issue by vipints** [alexdlaird/django-dropzone-to-s3#1]
Hi @alexdlaird, 

Thanks for providing the piece of software for uploading files to S3 bucket. I am confused here with the `form` definition to render the html page `home.html` at your application. I am not seeing any `form.py` in your package folder. Is this fine to run the application without the form definitions? 

Thanks! 
Vipin

**Comment by alexdlaird** [comment]
@vipints The logic could easily be put into a Django form (and it should be, honestly), but it's currently just handled in the view. I wanted to introduce as view concepts as possible for the tutorial.

https://github.com/alexdlaird/django-dropzone-to-s3/blob/master/dropzone/views.py#L45
